name: my-app-backend Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
      
    - name: Build backend
      run: |
        cd backend
        npm run build
      
    - name: Test backend
      run: |
        cd backend
        npm test
      
    - name: Deploy backend
      env:
        HOST: ${{ secrets.HOST }}
        USER: jesse
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --delete ./backend/build/ ${USER}@${HOST}:/home/jesse/app/backend/
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} 'cd /home/jesse/app/backend && npm install && pm2 restart app'
