name: Express.js Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.17.0'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.HOST }}
        USER: jesse
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --delete ./ ${USER}@${HOST}:/home/jesse/app/backend/ --exclude .git --exclude node_modules
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd /home/jesse/app/backend && 
          npm ci --only=production && 
          pm2 restart app || pm2 start npm --name "app" -- start --env production -- -- --port 3000
          
    
    - name: Clean up
      if: always()
      run: rm -f private_key
